# fly.toml app configuration file generated for marstore on 2023-07-02T22:26:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marstore"
primary_region = "ams"

[build]
  image = "markaskli/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NNEBRE0YV2VN94EJEG4Xk0QSmGMBHlht9BDgKAQqwNmkHRJMAu9IVCgPpVJFGntiF0zNHiuyAmEBOzq7N4CsNUy00qSuzMzNA"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
